apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: my-app-vue
  name: my-app-vue
spec:
  replicas: 2
  selector:
    matchLabels:
      run: my-app-vue
  template:
    metadata:
      labels:
        run: my-app-vue
    spec:
      containers:
      - image: gcr.io/[mystic-subject-338316]/my-app-vue:latest #Replace [PROJECT-ID] accordingly
        name: my-app-vue
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: my-app-vue
spec:
  selector:
     run: my-app-vue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

